server.port=8080
spring.application.name=OnlineBookstore

# Disable Spring Security auto block
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Data folder path
data.path=data/